In [2]:
import numpy as np

Soal 1a:

In [2]:
array_python = []

array_numpy = np.array([])

# Cek tipe variabel
print("Tipe array_python:", type(array_python))
print("Tipe array_numpy:", type(array_numpy))

Tipe array_python: <class 'list'>
Tipe array_numpy: <class 'numpy.ndarray'>


Soal 1b:

In [3]:
data = input("Masukkan daftar bilangan, pisahkan dengan koma: ").split(",")

array_python = data

array_numpy = np.array(data) 

print("Array Python:", array_python)
print("Array NumPy:", array_numpy)

Array Python: ['10', '50', '20']
Array NumPy: ['10' '50' '20']


Soal 2:

In [5]:
array_numpy = np.array([[1, 2, 3], [4, 5, 6]])
 
jumlah_dimensi = array_numpy.ndim

bentuk_array = array_numpy.shape

ukuran_array = array_numpy.size

tipe_data = type(array_numpy)

print("Jumlah dimensi:", jumlah_dimensi)
print("Bentuk array:", bentuk_array)
print("Ukuran array:", ukuran_array)
print("Tipe data array:", tipe_data)

Jumlah dimensi: 2
Bentuk array: (2, 3)
Ukuran array: 6
Tipe data array: <class 'numpy.ndarray'>


Soal 3a:

In [28]:
array = np.full((2, 3), 0)

print(array)

[[0 0 0]
 [0 0 0]]


Soal 3b:

In [27]:
array = np.full((3, 2, 4), 1)

print(array)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


Soal 3c:

In [17]:
array = np.random.random(5)

print(array)

[0.36143073 0.52685351 0.73205077 0.83135196 0.68531226]


Soal 3d:

In [21]:
array = np.arange(0, 11)

print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


Soal 3e:

In [25]:
array = np.linspace(0, 1, 5)

print(array)

[0.   0.25 0.5  0.75 1.  ]


Soal 3f:

In [26]:
array = np.full((2, 3), 7)

print(array)

[[7 7 7]
 [7 7 7]]


Soal 3g:

In [31]:
array = np.random.uniform(0, 1, 4)

print(array)

[0.47867463 0.30174006 0.29708716 0.34286322]


Soal 3h:

In [33]:
array = np.random.randint(1, 11, (3, 3))

print(array)

[[10  8  1]
 [ 8  4  6]
 [ 9  2  2]]


Soal 3i:

In [3]:
def perkalian(x, y):
    return x * y

array = np.fromfunction(perkalian, (3, 3), dtype=int)

print(array)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


Soal 4a:

In [35]:
kelas_A = np.array(['Afeef', 'Rafly', 'Arya'])
kelas_B = np.array(['Reza', 'Valen', 'Iksan'])

data_mahasiswa = np.concatenate((kelas_A, kelas_B))
print(data_mahasiswa)

['Afeef' 'Rafly' 'Arya' 'Reza' 'Valen' 'Iksan']


Soal 4b:

In [39]:
nilai_A = np.array([75, 80, 85])
nilai_B = np.array([70, 90, 95])

nilai_total = np.append(nilai_A, nilai_B)

print(nilai_total)

[75 80 85 70 90 95]


Soal 4c:

In [ ]:
nilai = np.array([85, 90, 95])

nilai_dengan_uts = np.insert(nilai, 1, 88)
print(nilai_dengan_uts)

[85 88 90 95]


Soal 4d:

In [ ]:
nilai_kelas_A = np.array([80, 85, 90])
nilai_kelas_B = np.array([75, 88, 92])

nilai_gabungan = np.insert(np.array([nilai_kelas_A]), [1], nilai_kelas_B, 0)
print(nilai_gabungan)

[[80 85 90]
 [75 88 92]]


Soal 5a:

In [ ]:
nilai_eksperimen = np.array([10, 15, 18, 22])

del_idx = int(input("masukkan index data yang ingin dihapus: "))

nilai_bersih = np.delete(nilai_eksperimen, del_idx)
print(nilai_bersih)

[10 18 22]


Soal 5b:

In [ ]:
hasil_tes = np.array([[85, 90, 88],
                      [78, 82, 84],
                      [93, 89, 92],
                      [75, 80, 85]])

print("Masukkan nomor kelompok dan urutan siswa, dengan dipisahkan oleh koma (,)")

target_hapus = input().split(',')
target_hapus = [int(s) - 1 for s in target_hapus]

hasil_tes_baru = np.delete(hasil_tes, target_hapus[0], 0)
hasil_tes_baru = np.delete(hasil_tes_baru, target_hapus[1], 1)

print(hasil_tes_baru)

Masukkan nomor kelompok dan urutan siswa, dengan dipisahkan oleh koma (,)
[[90 88]
 [82 84]
 [80 85]]


Soal 5c:

In [ ]:
data = np.array([10, 3, 15, 7, 22, 17])

batas_nilai = int(input("Masukkan batas nilai: "))

data_bersih = np.delete(data, data < batas_nilai)

print(data_bersih)

[15 22 17]


Soal 6a:

In [ ]:
harga_barang = np.array([35000, 25000, 50000, 45000, 30000])

harga_urut = np.sort(harga_barang)

print(harga_urut)

[25000 30000 35000 45000 50000]


Soal 6b:

In [ ]:
skor_siswa = np.array([[85, 78, 90], [92, 89, 85], [76, 84, 80]])

skor_urut = np.sort(skor_siswa)

print(skor_urut)

[[78 85 90]
 [85 89 92]
 [76 80 84]]


Soal 6c:

In [ ]:
data = np.array([[9, 4, 6], [3, 7, 1]])

data_urut = data.flatten()
data_urut = np.sort(data_urut)

print(data_urut)

[1 3 4 6 7 9]


Soal 7a:

In [ ]:
suhu = np.random.randint(20, 40, 30)

suhu_tertentu = np.array([suhu[4], suhu[9], suhu[24], suhu[29]])

rata_rata = suhu_tertentu.mean()

print(f"Suhu hari tertentu: {suhu_tertentu}")
print(f"Rata-rata: {rata_rata}")

Suhu hari tertentu: [30 34 21 32]
Rata-rata: 29.25


Soal 7b:

In [104]:
# Data pertumbuhan bakteri selama 10 hari
pertumbuhan_bakteri = np.array([100, 120, 240, 130, 150, 110, 220, 175, 160, 200])

# Ambil data setiap 2 hari
data_tertentu = pertumbuhan_bakteri[::2]

# Hitung total pertumbuhan
total_pertumbuhan = data_tertentu.sum()

print(f"Data bakteri: {data_tertentu}")
print(f"Total pertumbuhan: {total_pertumbuhan}")

Data bakteri: [100 240 150 220 160]
Total pertumbuhan: 870


Soal 7c:

In [105]:
stok_barang = np.array([41, 51, 75, 57, 92, 13, 35, 64, 24, 66])

# Filter barang dengan stok >= 50
stok_tersisa = np.delete(stok_barang, stok_barang < 50)

# Hitung total stok tersisa
total_stok = stok_tersisa.sum()

print(f"Stok barang tersisa: {stok_tersisa}")
print(f"Total stok tersisa: {total_stok}")

Stok barang tersisa: [51 75 57 92 64 66]
Total stok tersisa: 405


Soal 7d:

In [ ]:
nilai = np.array([[80, 75, 85, 90, 95],
                  [70, 85, 80, 75, 90],
                  [88, 92, 77, 80, 85],
                  [65, 70, 85, 95, 100]])

nilai_tertentu = np.array([nilai[2,1], nilai[2,3], nilai[2, 4]])

print(f"Nilai siswa: {nilai_tertentu}")

Nilai siswa: [92 80 85]


Soal 8a:

In [ ]:
data_asli = np.array([10, 15, 20, 25, 30])

data_copy = data_asli

informasi_perubahan = input("Masukkan indeks elemen dan nilai yang ingin diubah (dipisah dengan koma): ").split(',')
[index, value] = [int(s) for s in informasi_perubahan]

data_copy[index] = value

print("Data Copy:", data_copy)
print("Data Asli:", data_asli)

Data Copy: [10 20 20 25 30]
Data Asli: [10 20 20 25 30]


Soal 8b:

In [ ]:
data_cuaca = np.array([[30, 32, 35], [28, 27, 26], [33, 31, 29]])

data_cuaca_copy = np.copy(data_cuaca)

data_cuaca_copy[1,2] = 40

print("Data Cuaca Copy:\n", data_cuaca_copy)
print("Data Cuaca Asli:\n", data_cuaca)

Data Cuaca Copy:
 [[30 32 35]
 [28 27 40]
 [33 31 29]]
Data Cuaca Asli:
 [[30 32 35]
 [28 27 26]
 [33 31 29]]


Soal 9a:

In [110]:
# Data nilai ujian siswa dalam array
nilai_ujian = np.array([75, 80, 90, 85, 60])

# Temukan nilai maksimum
nilai_maksimum = nilai_ujian.max()

# Hitung nilai rata-rata
nilai_rata_rata = nilai_ujian.mean()

# Hitung selisih antara nilai maksimum dan rata-rata
selisih = abs(nilai_maksimum - nilai_rata_rata) 

# Tampilkan nilai maksimum dan selisihnya
print("Nilai Maksimum:", nilai_maksimum)
print("Selisih Maksimum dan Rata-rata:", selisih)

Nilai Maksimum: 90
Selisih Maksimum dan Rata-rata: 12.0


Soal 9b:

In [ ]:
waktu_renang = np.array([50.5, 52.0, 48.7, 49.8, 51.2])

waktu_tercepat = waktu_renang.min()  

waktu_rata_rata = waktu_renang.mean()

selisih_waktu = round(abs(waktu_tercepat - waktu_rata_rata))

print("Waktu Tercepat:", waktu_tercepat)
print("Selisih Waktu Tercepat dan Rata-rata:", selisih_waktu)

Waktu Tercepat: 48.7
Selisih Waktu Tercepat dan Rata-rata: 2


Soal 9c:

In [114]:
skor_tim_A = np.array([85, 78, 90, 88, 76])

total_skor = skor_tim_A.sum()  

rata_rata_skor = skor_tim_A.mean() 

print("Total Skor:", total_skor)
print("Rata-rata Skor per Putaran:", rata_rata_skor)

Total Skor: 417
Rata-rata Skor per Putaran: 83.4


Soal 9d:

In [ ]:
harga_penutupan = np.array([150.5, 152.0, 148.7, 149.8, 151.2])

rata_rata_harga = harga_penutupan.mean() 

perbandingan = harga_penutupan[-1] - rata_rata_harga

print("Rata-rata Harga Penutupan:", rata_rata_harga)
print("Harga Penutupan Terakhir dibanding Rata-rata:", perbandingan)

Rata-rata Harga Penutupan: 150.44
Harga Penutupan Terakhir dibanding Rata-rata: 0.7599999999999909


Soal 10a:

In [118]:
# Data mahasiswa (Nama, NIM, Jurusan)
data_mahasiswa = np.array([['Farah', 'Tiara', 'Imelda'], ['123', '456', '789'], ['IF', 'DS', 'RPL']])

# Ubah data_mahasiswa
data_1 = data_mahasiswa.transpose()

print("Data mahasiswa:")
print(data_1)

Data mahasiswa:
[['Farah' '123' 'IF']
 ['Tiara' '456' 'DS']
 ['Imelda' '789' 'RPL']]


Soal 10b:

In [120]:
# Data nilai mahasiswa
nilai = np.array([80, 90, 85, 78, 92, 88])

# Bentuk ulang array nilai menjadi 2D dengan 3 kolom
nilai_1 = nilai.reshape((2, 3))


print("Array nilai:")
print(nilai_1)

Array nilai:
[[80 90 85]
 [78 92 88]]


Soal 10c:

In [121]:
penjualan = np.array([120, 150, 180, 100, 130, 170])

penjualan_1 = penjualan.reshape((3, 2)).transpose()

print("Data penjualan:")
print(penjualan_1)

Data penjualan:
[[120 180 130]
 [150 100 170]]


Soal 11:

In [134]:
data_statistik = np.array([
    [8, 8, 7], 
    [10, 7, 9], 
    [8, 8, 6], 
    [6, 7, 6], 
    [6, 6, 9], 
    [9, 6, 6], 
    [6, 6, 7], 
    [6, 7, 6], 
    [8, 9, 10], 
    [6, 7, 6]
])
print("Data Statistik Asli:")
print(data_statistik)

subset_data = np.delete(data_statistik, data_statistik.mean(1) < 7, axis=0)
print("Subset Data Statistik: ")
print(subset_data)

copy_data = np.copy(subset_data)
performa_tim_per_hari = copy_data.transpose()
print("Data setelah di transpose: ")
print(performa_tim_per_hari)

rata_rata_performa_tim_per_hari = performa_tim_per_hari.mean(1)
for rata_rata, tim in zip(rata_rata_performa_tim_per_hari, ['A', 'B', 'C']):
    print(f'Rata - Rata Performa Team {tim}: {rata_rata}')

Data Statistik Asli:
[[ 8  8  7]
 [10  7  9]
 [ 8  8  6]
 [ 6  7  6]
 [ 6  6  9]
 [ 9  6  6]
 [ 6  6  7]
 [ 6  7  6]
 [ 8  9 10]
 [ 6  7  6]]
Subset Data Statistik: 
[[ 8  8  7]
 [10  7  9]
 [ 8  8  6]
 [ 6  6  9]
 [ 9  6  6]
 [ 8  9 10]]
Data setelah di transpose: 
[[ 8 10  8  6  9  8]
 [ 8  7  8  6  6  9]
 [ 7  9  6  9  6 10]]
Rata - Rata Performa Team A: 8.166666666666666
Rata - Rata Performa Team B: 7.333333333333333
Rata - Rata Performa Team C: 7.833333333333333
